### ISSUE TITLE
Message on GitHiub

### ISSUE THREAD

**Issue by rogermichaelm** [IT110UMBForReal/RepoPWStudent#1]
@pwstudent I cannot find a way to "send a message" via github. It seems this functionality doesn't exist? Since you are the owner of our "team" for IT110 I am assumung you are Alex? Please reply to confirm or deny as I need assistance and clarification regarding my current repository and effort in the django project.

Thank you.

**Comment by rogermichaelm** [comment]
@pwstudent I am unfamiliar with GitHub. Does closing the issue mean something other than you are finished with it, or are otherwise disregarding it? When I close issues at my job, I message the requester and alert them. I explain why I have decided the issue should be closed. Then I ask if they need clarification or further assistance.

Is there a reply somewhere I am unaware of? Please advise?

**Comment by pwstudent** [comment]
Well, this is one way that a message can be sent, is it not? regardless, emails to afairley@cs.umb.edu are fine as well, although it would be ideal to get things binned in a task oriented queue instead. That workflow improvement will probably have to wait until next semester, when I intend to make much heavier use of github.

**Comment by rogermichaelm** [comment]
It is. I just was unaware of it, and when I a Googled send a message on
GitHub it wasn't clear that it was possible.

So, might I please be provided feedback regarding my work and what I might
to to improve it?

On Wednesday, December 16, 2015, 箱男 notifications@github.com wrote:

> Well, this is one way that a message can be sent, is it not? regardless,
> emails to afairley@cs.umb.edu
> <javascript:_e(%7B%7D,'cvml','afairley@cs.umb.edu');> are fine as well,
> although it would be ideal to get things binned in a task oriented queue
> instead. That workflow improvement will probably have to wait until next
> semester, when I intend to make much heavier use of github.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IT110UMBForReal/RepoPWStudent/issues/1#issuecomment-164996030
> .

## 

Sent from my iPhone

Roger Michael McNall
Mobile – 781.708.2575
rogermichaelm@gmail.com
Facebook: https://www.facebook.com/rogermichaelm
LinkedIn: www.linkedin.com/in/rogermichaelm
Twitter: https://twitter.com/helpdesksocial

**Comment by pwstudent** [comment]
Absolutely, as time allows.

**Comment by pwstudent** [comment]
You can also fork people's repositories and suggest they add a new file that contains a message.

**Comment by rogermichaelm** [comment]
Ok?

On Sunday, December 20, 2015, 箱男 notifications@github.com wrote:

> You can also fork people's repositories and suggest they add a new file
> that contains a message.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IT110UMBForReal/RepoPWStudent/issues/1#issuecomment-166199460
> .

## 

Sent from my iPhone

Roger Michael McNall
Mobile – 781.708.2575
rogermichaelm@gmail.com
Facebook: https://www.facebook.com/rogermichaelm
LinkedIn: www.linkedin.com/in/rogermichaelm
Twitter: https://twitter.com/helpdesksocial
